### ISSUE TITLE
Bug introduced by @masbug refactoring

### ISSUE THREAD

**Issue by iget-master** [spatie/dropbox-api#37] opened 2018-01-18 04:19 UTC
Hi,

We are experiencing an issue with uploading files from a `popen` stream.

The issue was introduced after this commit https://github.com/spatie/dropbox-api/commit/4ac2101bcc6d624ae66f6b14caf9967f7af0d2b7. 

The changes were welcome since it reduces memory usage peaks, but the problem is that for some reason, it don't read streams originated from popen(). Tracking the bug, I stopped on this line: https://github.com/spatie/dropbox-api/blob/af8d429a51422159da3ebaeaaf6cf1691e2bd561/src/Client.php#L559

For some reason GuzzleHttp client don't read this kind of streams (not seekable and not buffered), there are a few issues on this (see https://github.com/guzzle/guzzle/issues/1654 for example).

That was the reason that I made it loading chunks to memory instead of streaming it to Guzzle.

Our backup routines are broken due this changes. When I made this piece of code, I've researched a lot about this guzzle issue, and didn't found any workaround.

So I whould appreciate if @masbug can help us to find a great solution to this problem.

**Comment by iget-master** [comment] 2018-01-18 04:21
Actually, the problem isn't on Guzzle itself, but on guzzle/PSR7. I've made a PR to solve this, but there's no answers, the repository is just stopped there. See https://github.com/guzzle/psr7/issues/155

**Comment by masbug** [comment] 2018-01-18 09:23
Hello,

I am sorry to hear that. https://github.com/guzzle/guzzle/issues/1654 has been solved (I tested it as it's written and it works correctly - at least in my env.).

I tested dropbox api with popen but I cannot reproduce the issue. This is my setup:
// when creating a dropbox adapter I changed chunk size to 100 to trigger chunked upload
$handle = popen("dir", "r"); // simple dir command
$fs->writeStream('/popen_test/test2.txt', $handle); // write to dropbox via Flysystem

I also tried without changing chunk size so that whole upload is made in one go.

My env.:
guzzlehttp/psr7:  1.4.2
guzzlehttp/guzzle: 6.3.0
Windows 10
PHP 7.0.21

Looking at the other related issues I suspect this might be system related.

Can you post an example that triggers the issue on your side and your env. specs?

BR

**Comment by iget-master** [comment] 2018-01-19 17:38
My usecase is this:

```
    $resource =  popen("mysqldump -h ${host} -u ${username} -p${password} ${database} | gzip -c", 'r');
    $response = app('dropbox')->upload($path, $resource);
```

Note that I use a pipe to *GZIP* the `mysqldump` content, didn't tested yet but almost sure that using just the `mysqldump` would not fail.

My environment is Linux:

> Ubuntu 16.04.3 LTS (over a docker container)
> PHP 7.1.11-1+ubuntu16.04.1+deb.sury.org+1 
> guzzlehttp/psr7: 1.4.2
> guzzlehttp/guzzle: 6.3.0

**Comment by masbug** [comment] 2018-01-22 10:12
I am able to reproduce this issue now. Interestingly it only happens on Linux.
I've pushed a fix which works around this issue https://github.com/spatie/dropbox-api/pull/39 and tested it on Linux and Windows.

Best regards

**Closed** 2018-05-23 10:00 UTC

**Comment by masbug** [comment] 2018-07-18 13:59
This issue should not be closed. Please see pull #39
